spring:
  application:
    name: gochubat
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  access-expiration: 1800000
  refresh-expiration: 1209600000

naver:
  authorize-base-url: https://nid.naver.com/oauth2.0/authorize
  token-base-url: https://nid.naver.com/oauth2.0/token
  user-info-base-url: https://openapi.naver.com/v1/nid/me
  success-redirect-url: http://localhost:5173/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.gochubat: INFO
