spring:
  application:
    name: gochubat
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  access-expiration: 1800000
  refresh-expiration: 1209600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.gochubat: INFO
